In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[10, 10, 10],
       [ 7,  6,  5],
       [ 5, 10,  8]])

In [4]:
B

array([[-1,  2,  2],
       [ 2,  2,  3],
       [ 1, -1,  0]])

In [5]:
# Поэлементное умножение
A*B

array([[-10,  20,  20],
       [ 14,  12,  15],
       [  5, -10,   0]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[20 30 50]
 [10 21 32]
 [23 22 40]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[20, 30, 50],
       [10, 21, 32],
       [23, 22, 40]])

In [8]:
# Матричное умножение
A@B

array([[20, 30, 50],
       [10, 21, 32],
       [23, 22, 40]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[14, 22, 16],
       [49, 62, 54],
       [ 3,  4,  5]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 6  8  5 10  6]
 [ 8  5 10  9  8]
 [10  8  9 11  9]]
B:
 [[ 1  1]
 [ 0  3]
 [-1 -1]
 [ 1  2]
 [ 1  0]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[17, 45],
       [15, 31],
       [21, 47]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 3  1 -1 -3]
 [ 0  1 -4 -3]
 [ 2  2  2 -4]
 [-2 -1 -4 -2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 3  2  0  3]
 [ 0  2  0  3]
 [ 2  4  0  4]
 [-2 -2  0  2]]
DA:
 [[ 3  1 -1 -3]
 [ 0  2 -8 -6]
 [ 0  0  0  0]
 [ 2  1  4  2]]


In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [16]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [19]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__________

In [22]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [23]:
A@x

array([26, 30])

In [24]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [25]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [26]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [28]:
A = np.array([x,y,z])

In [29]:
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [31]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [32]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [33]:
(Count_DF * Price_DF) @ com

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64

In [39]:
income = np.ones((5)) - com
income

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [40]:
(Count_DF * Price_DF) @ income

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64